[package]
name = "termsize"
version = "0.1.0"
authors = ["Nicolas Koch <nioko1337@gmail.com>"]
build = "build.rs"

[dependencies]
libc = "*"

# Windows stuff
winapi = "*"
kernel32-sys = "*"

[dev-dependencies]
regex = "*"

[build-dependencies]
gcc = "*"
